name: Run unit tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - ready_for_review
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check poetry
        run: |
          poetry --version
          poetry config --list

      - name: Install dependencies
        run: |
          poetry install
          ./poetry_plugins.sh

      - name: Run unit tests
        run: |
          make test
